<template>
  <div class="about-page">
    <h1>Animeloop Beta</h1>
    <!-- eslint-disable max-len -->
    <p>
      <a href="https://github.com/OrcaXS/animeloop-web-nuxt">Animeloop-web-nuxt</a> is an open-source web app built with <a href="https://nuxtjs.org">Nuxt.js</a>, aims to provide better experience than the original Animeloop-server. <br> Currently serves as Animeloop Beta.
    </p>
    <p>
      Animeloop belongs to <a href="https://moeoverflow.org/">MOEOVERFLOW</a> organization, the main goal is to collect some interesting loop fragments in Japanese anime video. All of the content of the site is generated by <a href="https://github.com/moeoverflow/animeloop-cli">animeloop-cli</a>. As you can see, the fragments that are currently generated are not much ideal, and the algorithms are constantly being slowly optimized.
    </p>
    <p>
      This site has a set of automated procedures (automator) in the background server running at day and night, the speed for generating new content is about two season anime per one day.
    </p>
    <p>
      Currrently the new content source to generate provided by administrator manually, and in the future, the source will be added by automator from dmhy.org etc with a full Automator.
    </p>
    <p>
      Site development plan, at this stage, the main focus on the development of server automation, the goal is high stability in the automatic operation.
    </p>
    <p>
      In addition, special thanks to <a href="https://whatanime.ga/">whatanime.ga</a> provided by the animation screenshot recognition service support. Thanks to <a href="https://twitter.com/democyann">呆萌ちゃん</a> for Japanese translation, <a href="https://src.moe/">POJO</a> for French translation.
    </p>
    <!-- eslint-enable max-len -->
  </div>
</template>

<script>
export default {
  name: 'About',

  head() {
    return {
      title: 'About | Animeloop',
    };
  },

  data() {
    return {
    };
  },
};
</script>

<style scoped lang="postcss">
.about-page {
  padding: 0 1em;
  margin-left: auto;
  margin-right: auto;
  max-width: 50em;

  & > p {
    margin: 1em 0;
    color: #333;
  }

  & a {
    color: royalblue;
    font-weight: 500;
  }
}
</style>
