<template>
  <div class="about-page">
    <h1>Animeloop-web-nuxt</h1>
    <p>
      Animeloop belongs to MOEOVERFLOW organization, the main goal is to collect some interesting loop fragments in Japanese anime video. All of the content of the site is generated by animeloop-cli. As you can see, the fragments that are currently generated are not much ideal, and the algorithms are constantly being slowly optimized.
    </p>
  </div>
</template>

<script>
export default {
  name: 'About',

  head() {
    return {
      title: `${this.$t('about')} | Animeloop`,
    };
  },

  data() {
    return {
    };
  },
};
</script>

<style scoped>
.about-page {
  margin: 1em;
}
</style>
